apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: sales
  description: Everything about sales apps
spec:
  owner: team-rudl
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: silly-system
  description: This System is all fake
  links:
    - url: https://www.google.at
      title: Silly System PROD
spec:
  owner: team-rudl
  domain: sales
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pet-store
  annotations:
    backstage.io/techdocs-ref: dir:.
  description: The Pet Store REST API
spec:
  type: openapi
  lifecycle: production
  owner: team-rudl
  system: silly-system
  definition: 
    $openapi: https://petstore.swagger.io/v2/swagger.json
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: magic-api
  annotations:
    backstage.io/techdocs-ref: dir:.
  description: The magic REST API
spec:
  type: openapi
  lifecycle: production
  owner: team-rudl
  system: silly-system
  definition: 
    $openapi: ./spec/openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  description: The unicorn is the coolest and most wonderful thing which our company has every created! I wish we open-source it and share it with the whole world!
  annotations:
    github.com/project-readme-path: README.md
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: squerzy/backstage-sample-application-1
    backstage.io/source-location: url:https://github.com/squerzy/backstage-sample-application-1/
  name: magic-unicorn-svc
  tags:
    - silly
    - brainfuck
  links:
  - url: https://www.google.com
    title: Magic Unicorn Homepage
    icon: home
  - url: https://www.google.com
    title: Documentation
    icon: article 
  - url: https://www.google.com
    title: Book a date with the unicorn
    icon: favorite
spec:
  dependsOn:
    - resource:default/magic-unicorn-s3
  providesApis:
    - magic-api
  consumesApis:
    - pet-store
  system: silly-system
  children: []
  lifecycle: production
  owner: team-rudl
  type: service
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: magic-unicorn-s3
  description: S3 bucket holding magic stuff
spec:
  type: s3
  owner: team-rudl
  system: silly-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: magic-unicorn-web
  description: This is a really cool subcomponent of the magic unicorn.
  tags:
    - cool
    - really-cool
spec:
  system: silly-system
  subcomponentOf: component:default/magic-unicorn-svc
  consumesApis:
    - pet-store
  type: website
  lifecycle: production
  owner: team-rudl
