apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: sales
  description: Everything about sales apps
spec:
  owner: team-rudl
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: silly-system
  description: This System is all fake
spec:
  owner: team-rudl
  domain: sales
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-readme-path: README.md
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/squerzy/backstate-sample-application-1/
  name: magic-unicorn
  links:
  - url: https://www.google.com
    title: Magic Unicorn Homepage
    icon: home
  - url: https://www.google.com
    title: Documentation
    icon: article 
  - url: https://www.google.com
    title: Book a date with the unicorn
    icon: favorite
spec:
  system: silly-system
  children: []
  lifecycle: production
  owner: team-rudl
  type: service
